name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run tests (if present)
        run: |
          if [ -d tests ] || [ -f pytest.ini ] || [ -f pyproject.toml ]; then
            pytest -q || true
          else
            echo "No tests configured"
          fi

